[project]
name = "asteroids"
version = "0.1.0"
description = "A simple 2D Asteroids-style game implemented in Python."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pygame==2.6.1",
]
